language: python

python:
  - 3.6

services:
  - docker

before_install:
  - export PYTHONPATH=$HOME/builds/jay-johnson/metalnetes
  - export PIP_USE_MIRRORS=true
  - export USE_VERSION=$(cat setup.py | grep " version=" | sed -e 's/"/ /g' | sed -e "s/'/ /g" | awk '{print $2}')
  - export REPO=jayjohnson/metalnetes
  - echo "is TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}"

install:
  - pip install -e .

script:
  - echo "Running Lint Tests"
  - flake8 .
  - pycodestyle --exclude=.tox,.eggs
  - echo "Running Unit Tests"
  - py.test

after_success:
  - export USE_VERSION=$(cat setup.py | grep " version=" | sed -e 's/"/ /g' | sed -e "s/'/ /g" | awk '{print $2}')
  - echo "Test Success - Branch=${TRAVIS_BRANCH} Version=${USE_VERSION} Pull Request=${TRAVIS_PULL_REQUEST} Tag=${TRAVIS_TAG}"
